import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Page About",
  description: "Generated by create by next js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            test
            {children}
        </body>
    </html>
  );
}
