import type { Metadata } from "next";
import { ThemeProvider } from "./context/ThemeContext";
import NavBar from "./components/NavBar";
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ThemeProvider>
      <html lang="fr">
        <body
          className="min-h-screen"
        >
          <NavBar/>
            {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
